from fastapi import APIRouter, UploadFile, File
from fastapi.responses import JSONResponse
from pydantic import BaseModel
from typing import List, Optional
import os
import hashlib
import re
import uuid

router = APIRouter(tags=["ingest"])

from app.paths import DATA_DIR as EXAM_TRACKER_DIR
RAW_DIR = f"{EXAM_TRACKER_DIR}/raw"

TOKEN_RE = re.compile(r"^[0-9a-f]{32}(?:\.xlsx)?$")


def save_upload_with_content(filename: str, content: bytes) -> tuple[str, str]:
    """Save an upload under a server-generated token, never the client filename."""
    os.makedirs(RAW_DIR, exist_ok=True)
    suffix = ".xlsx" if (filename or "").lower().endswith(".xlsx") else ""
    token = f"{uuid.uuid4().hex}{suffix}"
    file_path = os.path.join(RAW_DIR, token)
    with open(file_path, "wb") as f:
        f.write(content)
    return token, file_path

def resolve_token_path(token: str) -> str:
    """Resolve only opaque tokens generated by this service."""
    if not TOKEN_RE.fullmatch(token or ""):
        raise ValueError("无效的上传令牌")
    return os.path.join(RAW_DIR, token)

def compute_hash(content: bytes) -> str:
    return hashlib.md5(content).hexdigest()

def detect_class_from_students(students: list) -> Optional[int]:
    """从学生列表众数统计检测班级号"""
    class_counts = {}
    for s in students:
        cls = s.get("class_num") or s.get("class")
        if cls:
            class_counts[cls] = class_counts.get(cls, 0) + 1
    if class_counts:
        return max(class_counts, key=class_counts.get)
    return None

def split_sort_key(sort_key: Optional[str]) -> tuple[Optional[int], Optional[int]]:
    """把 'YYYY-MM' 拆成 (year, month)，供前端预填年/月下拉。"""
    if not sort_key or "-" not in sort_key:
        return None, None
    try:
        y, m = sort_key.split("-", 1)
        return int(y), int(m)
    except (ValueError, TypeError):
        return None, None

def _detect_sid_name_conflicts(db, subject_scores: list) -> Optional[str]:
    """学号-姓名冲突检测：本文件内同学号多姓名，或与库内已有姓名不一致。

    返回 None 表示无冲突；有冲突返回可直接展示给老师的报错文案。

    调用顺序契约：必须在 sid_space.ensure_sid_space **之后**调用——跨届
    撞号时守门已把旧届整体 G{g}:: 前缀化让位，此处查到的裸学号已全属
    本届，剩下的「同学号不同姓名」才是真正需要人工核对的错误数据；
    若放在守门之前，跨届合法重号会被误拒。
    """
    from app.db.models import SubjectScore

    incoming: dict[str, set[str]] = {}
    for ss in subject_scores:
        sid = (ss.get("student_id") or "").strip()
        nm = (ss.get("name") or "").strip()
        if sid and nm:
            incoming.setdefault(sid, set()).add(nm)

    # 本文件内：同学号多姓名（Excel 错行/两班混排）
    internal = [
        (sid, sorted(nms)) for sid, nms in incoming.items() if len(nms) > 1
    ]
    if internal:
        detail = "；".join(f"{sid}：{'、'.join(nms)}" for sid, nms in internal[:5])
        return (
            f"文件内同一学号对应多个姓名（{detail}），已拒绝写入。"
            "请检查 Excel 是否混入其他班级的数据。"
        )

    # 与库内：已入库的该学号姓名与本次不同（守门后仍同名不同人 = 同届内录错学号）
    sids = [sid for sid, nms in incoming.items() if len(nms) == 1]
    conflicts = []
    if sids:
        rows = (
            db.query(SubjectScore.student_id, SubjectScore.name)
            .filter(
                SubjectScore.student_id.in_(sids),
                SubjectScore.name.isnot(None),
            )
            .distinct()
            .all()
        )
        for sid, nm in rows:
            nm = (nm or "").strip()
            if nm and nm not in incoming.get(sid, set()):
                conflicts.append((sid, nm, next(iter(incoming[sid]))))
    if conflicts:
        detail = "；".join(
            f"{sid} 库内=「{old}」 本次=「{new}」" for sid, old, new in conflicts[:5]
        )
        return (
            f"学号与历史数据姓名不一致（{detail}），已拒绝写入。"
            "请核对该学号是否属于本次考试学生；"
            "确为同一人请先统一姓名后重传。"
        )
    return None


def get_or_create_exam(db, parsed: dict, grade: int, file_path: str):
    from app.db.models import Exam

    exam = db.query(Exam).filter(
        Exam.grade == grade,
        Exam.semester == (parsed["semester"] or "下"),
        Exam.exam_date == parsed["sort_key"],
        Exam.exam_type == (parsed["exam_type"] or "月考"),
    ).first()
    if not exam:
        exam = Exam(
            name=parsed["canonical_name"],
            grade=grade,
            semester=parsed["semester"] or "下",
            exam_date=parsed["sort_key"],
            exam_type=parsed["exam_type"] or "月考",
            source_files=[file_path],
        )
        db.add(exam)
        db.flush()
    else:
        if exam.name != parsed["canonical_name"]:
            exam.name = parsed["canonical_name"]
        if file_path not in (exam.source_files or []):
            exam.source_files = (exam.source_files or []) + [file_path]
    return exam


def parse_and_store(file_path: str, filename: str, parsed: dict, grade: int) -> dict:
    """解析单个 Excel 文件并写库。parsed 提供 semester/exam_type/sort_key/canonical_name。
    返回 {result, detected_class, detected_grade}；调用方负责汇总。"""
    from app.db.models import SessionLocal, Upload, SubjectScore, TotalScore, ClassAverage

    out = {"result": None, "detected_class": None, "detected_grade": None}

    filename = filename or "upload"
    if not filename.lower().endswith('.xlsx'):
        out["result"] = {
            "filename": filename,
            "parsed_ok": False,
            "message": "暂不支持此文件类型，请上传学生成绩明细表或班级均分表 Excel（.xlsx）",
        }
        return out

    db = SessionLocal()
    try:
        # 根据年级选择解析器
        if grade == 1:
            from app.ingest.excel_parser import parse_excel_grade1
            result = parse_excel_grade1(file_path)
        else:
            from app.ingest.excel_parser import parse_excel_grade23
            result = parse_excel_grade23(file_path, grade)

        kind = result.get("kind")
        parsed_ok = kind in {"student_scores", "class_averages"}

        upload_record = Upload(
            file_path=file_path,
            file_hash=compute_hash(open(file_path, "rb").read()),
            kind=kind or "unknown",
            mime="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
            parsed_ok=1 if parsed_ok else 0,
            parse_log=result if not parsed_ok else None,
        )
        db.add(upload_record)

        if kind == "student_scores":
            students = result.get("students", [])
            subject_scores = result.get("subject_scores", [])
            total_scores = result.get("total_scores", [])

            out["detected_class"] = detect_class_from_students(students)
            out["detected_grade"] = grade

            # 跨届学号守门（必须先于撞号防呆）：本届成绩学号若与旧届裸学号
            # 撞车（每学年重新编学号的学校），先把旧届整体 G{g}:: 前缀化
            # 让位再写裸号；与本次写入同一事务，解析失败整体回滚。守门之后
            # 库内裸学号已全属本届，防呆的「与库内姓名不一致」只剩同届内
            # 录错学号的真冲突，不会误拒跨届合法重号。
            from app.db.sid_space import ensure_sid_space

            incoming_sids = {
                ss["student_id"] for ss in subject_scores if ss.get("student_id")
            }
            if incoming_sids:
                ensure_sid_space(
                    db, incoming_sids, grade, commit=False, auto_backup=True
                )

            # 撞号防呆：学号是「人」的全局标识，同学号不同姓名会把两个学生
            # 的成绩/总分混到同一人名下（跨学年画像按人聚合）。写库前整文件
            # 拒绝并明确报错，引导人工核对。
            conflict = _detect_sid_name_conflicts(db, subject_scores)
            if conflict:
                db.rollback()
                out["result"] = {
                    "filename": filename,
                    "parsed_ok": False,
                    "message": conflict,
                }
                return out

            exam = get_or_create_exam(db, parsed, grade, file_path)
            upload_record.exam_id = exam.id

            for ss in subject_scores:
                db.add(SubjectScore(
                    exam_id=exam.id,
                    student_id=ss["student_id"],
                    class_num=ss.get("class_num"),
                    xueji=ss.get("xueji"),
                    name=ss.get("name"),
                    subject=ss["subject"],
                    raw_score=ss.get("raw_score"),
                    grade_score=ss.get("grade_score"),
                    grade_percentile=ss.get("grade_percentile"),
                ))

            for ts in total_scores:
                db.add(TotalScore(
                    exam_id=exam.id,
                    student_id=ts["student_id"],
                    total_type=ts["total_type"],
                    total_score=ts.get("total_score"),
                    grade_percentile=ts.get("grade_percentile"),
                    xueji_rank=ts.get("xueji_rank"),
                    grade_rank=ts.get("grade_rank"),
                ))

            db.commit()
            out["result"] = {
                "filename": filename,
                "parsed_ok": True,
                "message": f"解析成功，检测到{len(students)}名学生 · 归入「{parsed['canonical_name']}」",
                "kind": "student_scores",
                "grade": grade,
                "exam_name": parsed["canonical_name"],
            }

        elif kind == "class_averages":
            class_avgs = result.get("class_averages", [])
            exam = get_or_create_exam(db, parsed, grade, file_path)
            upload_record.exam_id = exam.id

            for ca in class_avgs:
                db.add(ClassAverage(
                    exam_id=exam.id,
                    class_type=ca.get("class_type"),
                    class_num=ca.get("class_num"),
                    teacher_name=ca.get("teacher_name"),
                    subject_averages=ca.get("subject_averages", {}),
                    total_averages=ca.get("total_averages", {}),
                ))

            db.commit()
            out["result"] = {
                "filename": filename,
                "parsed_ok": True,
                "message": f"解析成功，检测到{len(class_avgs)}个班级均分 · 归入「{parsed['canonical_name']}」",
                "kind": "class_averages",
                "grade": grade,
                "exam_name": parsed["canonical_name"],
            }

        else:
            db.commit()
            out["result"] = {
                "filename": filename,
                "parsed_ok": False,
                "message": f"未知文件类型: {kind}",
            }

    except Exception as e:
        db.rollback()
        out["result"] = {
            "filename": filename,
            "parsed_ok": False,
            "message": str(e),
        }
    finally:
        db.close()

    return out


@router.post("/uploads/preview")
async def preview_files(files: List[UploadFile] = File(...)):
    """阶段一：保存文件并按文件名给出可编辑的元数据建议，不入库。"""
    from app.ingest.filename_parser import parse_filename

    items = []
    for file in files:
        content = await file.read()
        filename = file.filename or "upload"
        token, _ = save_upload_with_content(filename, content)

        parsed = parse_filename(filename)
        year, month = split_sort_key(parsed.get("sort_key"))
        items.append({
            "token": token,
            "filename": filename,
            "grade": parsed.get("grade") or 1,
            "semester": parsed.get("semester") or "上",
            "exam_type": parsed.get("exam_type") or "月考",
            "year": year,
            "month": month,
            "canonical_name": parsed.get("canonical_name"),
            "is_xlsx": filename.lower().endswith(".xlsx"),
        })

    return JSONResponse({"files": items})


class CommitItem(BaseModel):
    token: str
    filename: Optional[str] = None
    grade: int
    semester: str
    exam_type: str
    year: int
    month: int


class CommitRequest(BaseModel):
    items: List[CommitItem]


@router.post("/uploads/commit")
async def commit_files(payload: CommitRequest):
    """阶段二：按用户确认后的年级/学期/类型/年月正式解析入库。"""
    from app.ingest.filename_parser import build_exam_name

    results = []
    detected_class = None
    detected_grade = None

    for item in payload.items:
        try:
            file_path = resolve_token_path(item.token)
        except ValueError as exc:
            results.append({
                "filename": item.filename or "上传文件",
                "parsed_ok": False,
                "message": str(exc),
            })
            continue
        if not os.path.exists(file_path):
            results.append({
                "filename": item.filename or "上传文件",
                "parsed_ok": False,
                "message": "文件已失效，请重新选择并上传",
            })
            continue

        sort_key = f"{item.year}-{item.month:02d}"
        parsed = {
            "grade": item.grade,
            "semester": item.semester if item.semester in ("上", "下") else "上",
            "exam_type": item.exam_type,
            "sort_key": sort_key,
            "canonical_name": build_exam_name(item.grade, item.semester, item.exam_type, item.month),
        }
        display_name = os.path.basename(item.filename or "上传文件.xlsx")
        out = parse_and_store(file_path, display_name, parsed, item.grade)
        results.append(out["result"])
        if out["detected_class"]:
            detected_class = out["detected_class"]
            detected_grade = out["detected_grade"]

    response = {"results": results}
    if detected_class:
        response["detected_class"] = detected_class
        response["detected_grade"] = detected_grade or 1
        # 检测到比班主任已绑定的最高年级更高年级的数据 → 建议执行 rollover
        from app.db.models import SessionLocal, Teacher
        _db = SessionLocal()
        try:
            teacher = _db.query(Teacher).first()
            if teacher is not None:
                bound_max_grade = max(
                    {g for g, col in [(1, teacher.target_class_high1),
                                      (2, teacher.target_class_high2),
                                      (3, teacher.target_class_high3)] if col is not None},
                    default=0,
                )
                if detected_grade and detected_grade > bound_max_grade:
                    response["suggest_rollover"] = True
        finally:
            _db.close()
    return JSONResponse(response)


@router.post("/uploads")
async def upload_files(files: List[UploadFile] = File(...)):
    """旧版一步式上传：完全按文件名自动识别后直接入库（保留向后兼容）。"""
    from app.ingest.filename_parser import parse_filename

    results = []
    detected_class = None
    detected_grade = None

    for file in files:
        content = await file.read()
        filename = file.filename or "upload"
        _, file_path = save_upload_with_content(filename, content)

        parsed = parse_filename(filename)
        grade = parsed.get("grade") or 1

        out = parse_and_store(file_path, filename, parsed, grade)
        results.append(out["result"])
        if out["detected_class"]:
            detected_class = out["detected_class"]
            detected_grade = out["detected_grade"]

    response = {"results": results}
    if detected_class:
        response["detected_class"] = detected_class
        response["detected_grade"] = detected_grade or 1
        # 检测到比班主任已绑定的最高年级更高年级的数据 → 建议执行 rollover
        from app.db.models import SessionLocal, Teacher
        _db = SessionLocal()
        try:
            teacher = _db.query(Teacher).first()
            if teacher is not None:
                bound_max_grade = max(
                    {g for g, col in [(1, teacher.target_class_high1),
                                      (2, teacher.target_class_high2),
                                      (3, teacher.target_class_high3)] if col is not None},
                    default=0,
                )
                if detected_grade and detected_grade > bound_max_grade:
                    response["suggest_rollover"] = True
        finally:
            _db.close()
    return JSONResponse(response)


@router.get("/uploads")
async def list_uploads():
    """列出已上传文件"""
    from app.db.models import SessionLocal, Upload
    db = SessionLocal()
    uploads = db.query(Upload).order_by(Upload.uploaded_at.desc()).limit(50).all()
    db.close()
    return {
        "uploads": [{
            "id": u.id,
            "filename": u.file_path.split("/")[-1] if u.file_path else "",
            "kind": u.kind,
            "mime": u.mime,
            "parsed_ok": bool(u.parsed_ok),
            "exam_id": u.exam_id,
            "uploaded_at": u.uploaded_at.isoformat() if u.uploaded_at else None,
        } for u in uploads]
    }
